feat(markdown-models): add support for tables
accordproject/models pull request #159
Opened 2022-07-26 10:50 UTC by TC5022

Signed-off-by: TC5022 <tanyac5022002@gmail.com>

### Changes

- <ONE> This is a PR to introduce table extensions in the common mark and ciceromark models
- <TWO> This is required to complete the table transformations in other markdown formats

### Author Checklist
- [ ] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:branchname`

2022-07-26 13:15 UTC, dselman commented on src/markdown/commonmark@0.4.0.cto
> +concept HeaderCell extends TableCell{
Extends Child?

2022-07-26 13:16 UTC, dselman requested changes
HeaderCell should extend Child

2022-07-26 14:09 UTC, TC5022 commented
> HeaderCell should extend Child

Fixed it @dselman

2022-07-26 21:13 UTC, DianaLease approved these changes
👍

2022-07-28 13:39 UTC, dselman approved these changes

2022-07-28 13:39 UTC, merged